# Generated by Django 3.2.19 on 2023-05-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Appetizer', 'Appetizer'), ('Salad', 'Salad'), ('Baked-goods', 'Baked-goods'), ('Dessert', 'Dessert'), ('Soup', 'Soup'), ('Vegetarian', 'Vegetarian')], max_length=100),
        ),
    ]
