# Generated by Django 3.2.19 on 2023-05-12 21:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0002_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image 3'),
        ),
    ]
